---
run:
  concurrency: 6
  timeout: 5m
  modules-download-mode: readonly
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - exptostd
    - fatcontext
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - iface
    - inamedparam
    - ineffassign
    - interfacebloat
    - makezero
    - mirror
    - misspell
    - nilerr
    - nilnesserr
    - nolintlint
    - nosprintfhostport
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testableexamples
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
linters-settings:
  errcheck:
    check-blank: false
  nolintlint:
    allow-unused: true
    require-specific: true
  revive:
    rules:
    - name: unused-parameter
      disabled: true

issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
  exclude-dirs-use-default: true
  exclude-dirs:
    - contrib
    - dependencies
  exclude-rules:
    # Exclude recvcheck from running on the imported k8s files, to much failures
    - path: pkg/k8s.io/
      linters:
        - recvcheck
